### ISSUE TITLE
Trying to add FUSE network

### ISSUE THREAD

**Issue by henry-hz** [naddison36/tx2uml#32]
@naddison36  thanks for sharing tx2uml, it's an amazing tool!

I am having difficult to run with fuse network, they use OpenEthereum

```
→ curl --location --request POST 'https://rpc.fuse.io' \                                                                                         [403e814]
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"web3_clientVersion",
        "params":[],
        "id":1
}'
{"jsonrpc":"2.0","result":"OpenEthereum//v3.2.6-stable/x86_64-linux-musl/rustc1.47.0","id":1}
```

ChainID info:
```
{
  "name": "Fuse Mainnet",
  "chain": "FUSE",
  "rpc": [
    "https://rpc.fuse.io"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Fuse",
    "symbol": "FUSE",
    "decimals": 18
  },
  "infoURL": "https://fuse.io/",
  "shortName": "fuse",
  "chainId": 122,
  "networkId": 122
}
```

Here I point to the https://explorer-node.fuse.io/, once it is an archive node, and keeps the old txs.

```shell
 ./lib/tx2uml.js -n openeth -u https://explorer-node.fuse.io/ -v 0x569bc338ad122fe50f8347a280a74e89b820c8c508f7e4527137cc7956d68845                        [403e814]
  tx2uml Enabled tx2uml debug +0ms
  tx2uml Using OpenEthereum client. +1ms
Failed to generate UML diagram VError: Failed to get transaction details for tx hash 0x569bc338ad122fe50f8347a280a74e89b820c8c508f7e4527137cc7956d68845 from url https://rpc.fuse.io.: underlying network changed (event="changed", network={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"chainId":122,"name":"unknown"}, code=NETWORK_ERROR, version=providers/5.5.2)
    at OpenEthereumClient.getTransactionDetails (/home/henry/code/tx2uml/lib/clients/EthereumNodeClient.js:50:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async tx2uml (/home/henry/code/tx2uml/lib/tx2uml.js:89:27)
```

**Comment by sambacha** [comment]
I am planning on redeploy the contract via CREATE2 so multichain support will be easier.

**Comment by naddison36** [comment]
@henry-hz apologies for the slow response. Can you try the latest version v1.0.18?
The chain id is no longer set so it should for with FUSE

**Comment by naddison36** [comment]
Although tx2uml doesn't explicitly support FUSE, it will produce a transaction trace. It will try and get the verified contracts from Etherscan instead of the FUSE explorer.

Here's the example given above
![32-fuse](https://user-images.githubusercontent.com/6491112/226760045-0b4bb776-a99f-49f7-b882-c2410240b1cf.svg)
