### ISSUE TITLE
got an error 400 as response 

### ISSUE THREAD

**Issue by SvenMeyer** [naddison36/tx2uml#63]
I tried this ...
```
$ tx2uml call 0x6a96ee64eae15f3f952b91d06f68610b1ccd1b3ff9889d5c83f8856abfb5989d --url https://eth-mainnet.g.alchemy.com/v2/FdOOWIXXXXXXXXXXXXXXXXXXXX
```

and just got this ....

```
Error: Failed to get transaction trace for tx hash 0x6a96ee64eae15f3f952b91d06f68610b1ccd1b3ff9889d5c83f8856abfb5989d from url https://eth-mainnet.g.alchemy.com/v2/FdOOWIXXXXXXXXXXXXXXXXXXXXXXXXX.
    at GethClient.getTransactionTrace (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/lib/clients/GethClient.js:49:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionManager.getTraces (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/lib/transaction.js:36:37)
    at async generateCallDiagram (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/lib/callDiagram.js:31:41)
    at async Command.<anonymous> (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/lib/tx2uml.js:57:9)
    at async Command.parseAsync (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/node_modules/commander/lib/command.js:935:5)
    at async main (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/lib/tx2uml.js:116:5) {
  [cause]: AxiosError: Request failed with status code 400
      at settle (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/node_modules/axios/dist/node/axios.cjs:1900:12)
      at IncomingMessage.handleStreamEnd (/home/sum/.nvm/versions/node/v16.19.1/lib/node_modules/tx2uml/node_modules/axios/dist/node/axios.cjs:2952:11)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1358:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      method: 'post',
      url: 'https://eth-mainnet.g.alchemy.com/v2/FdOOWIXXXXXXXXXXXXXXXXXXXXXXXXXX',
      data: '{"id":0,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x6a96ee64eae15f3f952b91d06f68610b1ccd1b3ff9889d5c83f8856abfb5989d",{"tracer":"callTracer"}]}'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '162',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v2/FdOOWIXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Content-Length: 162\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: eth-mainnet.g.alchemy.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v2/FdOOWIXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'eth-mainnet.g.alchemy.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: [AxiosHeaders],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    }
  }
}
```

**Comment by naddison36** [comment]
Your node provider needs to support `debug_traceTransaction ` with the `callTracer` param or `trace_transaction`.

Alchemy only supports these on their paid growth plan

https://github.com/naddison36/tx2uml#archive-node-that-supports-tracing-transactions

**Comment by naddison36** [comment]
I'll make some changes to better report the error
